version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocyclo
    - goconst
  settings:
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3

formatters:
  enable:
    - gofmt
    - goimports
