FROM grafana/grafana:13.0.2

USER root
COPY deploy/grafana-entrypoint.sh /usr/local/bin/taskqueue-grafana-entrypoint
COPY grafana/provisioning /etc/grafana/provisioning
COPY grafana/dashboards /var/lib/grafana/dashboards
RUN chmod +x /usr/local/bin/taskqueue-grafana-entrypoint \
    && chown -R grafana:root /etc/grafana/provisioning /var/lib/grafana/dashboards

USER grafana
ENTRYPOINT ["/usr/local/bin/taskqueue-grafana-entrypoint"]
