FROM prom/prometheus:v3.12.0

USER root
COPY deploy/prometheus-entrypoint.sh /usr/local/bin/prometheus-entrypoint
COPY deploy/prometheus.render.yml /etc/prometheus/prometheus.render.yml
RUN chmod +x /usr/local/bin/prometheus-entrypoint

USER nobody
ENTRYPOINT ["/usr/local/bin/prometheus-entrypoint"]
